### ISSUE TITLE
命名方式要專業一點

### ISSUE THREAD

**Issue by pecu** [kennychenfs/YTP-2022#1]
雖然用中文沒有不對，但如果想要讓專案更容易走向國際化，減少中文編碼而產生的額外問題
請使用 https://codertw.com/%E7%A8%8B%E5%BC%8F%E8%AA%9E%E8%A8%80/555937/
程式設計命名規則：駝峰命名法和匈牙利命名法

並且思考一下之後你們專案想要用來進行訓練的資料會是甚麼，可以先嘗試用爬蟲開始收集了

請改好程式，重新 push 之後，關閉這個 issues

**Comment by kennyfs** [comment]
用駝峰命名法改好了👍
